FROM rust:1.92-trixie AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libapt-pkg-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml Cargo.lock ./
COPY src ./src
RUN cargo build --release

FROM debian:trixie-slim

RUN apt-get update \
    && apt-get install -y libapt-pkg7.0 \
    && apt full-upgrade -s

COPY --from=builder /app/target/release/cobblerd /usr/local/bin/cobblerd
ENTRYPOINT ["/usr/local/bin/cobblerd"]
