FROM rust:1.92-trixie
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libapt-pkg-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-deb --locked

COPY . .
WORKDIR /app/daemon
RUN cargo deb

FROM scratch
COPY --from=0 /app/daemon/target/debian/*.deb /
