FROM rust:1.92-trixie
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libapt-pkg-dev \
    pkg-config \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install.sh | sh
RUN cargo binstall -y cargo-deb

COPY . .
WORKDIR /app/daemon
RUN cargo deb

FROM scratch
COPY --from=0 /app/daemon/target/debian/*.deb /
